/**
 * Auto-bump patch version when git HEAD changes, then generate frontend version.ts.
 * Base release: v1.2.0 — each new commit increments patch (1.2.1, 1.2.2, …).
 */

import { execSync } from 'child_process'
import { readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const versionPath = join(root, 'version.json')
const versionTsPath = join(root, 'frontend', 'src', 'version.ts')

function gitHead() {
  try {
    return execSync('git rev-parse HEAD', { cwd: root, encoding: 'utf8' }).trim()
  } catch {
    return ''
  }
}

const version = JSON.parse(readFileSync(versionPath, 'utf8'))
const head = gitHead()

if (head) {
  if (!version.lastCommit) {
    version.lastCommit = head
    console.log(`Version initialized at v${version.major}.${version.minor}.${version.patch}`)
  } else if (head !== version.lastCommit) {
    version.patch = (version.patch ?? 0) + 1
    version.lastCommit = head
    console.log(`Version bumped to v${version.major}.${version.minor}.${version.patch}`)
  }
  writeFileSync(versionPath, `${JSON.stringify(version, null, 2)}\n`)
} else {
  console.log('Git not available; generating version file without bump')
}

const label = `v${version.major}.${version.minor}.${version.patch}`
const ts = `/** Auto-generated by scripts/bump-version.mjs — do not edit */
export const APP_VERSION = '${label}'
export const APP_VERSION_FULL = '${version.major}.${version.minor}.${version.patch}'
`

writeFileSync(versionTsPath, ts)
