/**
 * Manage app version (version.json + frontend/src/version.ts).
 *
 *   node scripts/bump-version.mjs        — sync version.ts from version.json (no bump)
 *   node scripts/bump-version.mjs --inc  — increment patch, then sync (use before each release commit)
 *
 * Base release: v1.2.0 — each intentional update increments patch (1.2.1, 1.2.2, …).
 */

import { execSync } from 'child_process'
import { readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const versionPath = join(root, 'version.json')
const versionTsPath = join(root, 'frontend', 'src', 'version.ts')
const shouldInc = process.argv.includes('--inc')

function gitHead() {
  try {
    return execSync('git rev-parse HEAD', { cwd: root, encoding: 'utf8' }).trim()
  } catch {
    return ''
  }
}

const version = JSON.parse(readFileSync(versionPath, 'utf8'))
const head = gitHead()

if (shouldInc) {
  version.patch = (version.patch ?? 0) + 1
  if (head) version.lastCommit = head
  console.log(`Version bumped to v${version.major}.${version.minor}.${version.patch}`)
  writeFileSync(versionPath, `${JSON.stringify(version, null, 2)}\n`)
} else if (head && !version.lastCommit) {
  version.lastCommit = head
  writeFileSync(versionPath, `${JSON.stringify(version, null, 2)}\n`)
  console.log(`Version initialized at v${version.major}.${version.minor}.${version.patch}`)
} else {
  console.log(`Version unchanged: v${version.major}.${version.minor}.${version.patch}`)
}

const label = `v${version.major}.${version.minor}.${version.patch}`
const ts = `/** Auto-generated by scripts/bump-version.mjs — do not edit */
export const APP_VERSION = '${label}'
export const APP_VERSION_FULL = '${version.major}.${version.minor}.${version.patch}'
`

writeFileSync(versionTsPath, ts)
